<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Guestbook</title>
		<link rel="stylesheet" type="text/css" href="<?=$this->getAppBasePath(); ?>/styles/simpletheme.css" />
	</head>

	<body>
		<div class="container">
			<header>
				<h1>Simple Guestbook</h1>
			</header>
			
			<div class="userBox">
				<?php if(!isset($this->userData)) : ?>
					<a href="<?=$this->getUrl("login"); ?>">login to write a new entry</a>
				<?php else: ?>
					Logged in as <?=$this->userData->getName();?>
					<a href="<?=$this->getUrl("logout"); ?>">logout</a>
				<?php endif; ?>
			</div>
			
			<div class="content">
				<?php if(isset($this->userData)) : ?>
				<div id="entryForm">
					<form method="post" action="<?=$this->getUrl("entry_send"); ?>">
						<label for="formText">Text</label>
						<textarea id="formText" name="text" cols=50 rows=10 placeholder="Write your entry here"></textarea>
						<button type="submit">Send your entry</button>
					</form>
				</div>
				<?php endif; ?>
				
				<div class="entryContainer">
					
					<h2>Entries</h2>

					<?php foreach($this->entries as $entry) :
						if((!isset($this->userData) || (!$this->userData->isAdmin() && $this->userData->getId() != $entry->getUserId())) && !$entry->isActive()) continue;
					?>
						<div class="entry<?=!$entry->isActive() ? ' inactive' : ''; ?>">

							<div class="rightSideRemarks">
								<?php if(isset($this->userData) && $this->userData->isAdmin()) : ?>
								<div class="entryControl">
									<?php if($entry->isActive()) : ?>
										<a href="<?=$this->getUrl("entry_unpublish"); ?>/?id=<?=$entry->getId();?>">unpublish</a> |
									<?php else: ?>
										<a class="publishLink" href="<?=$this->getUrl("entry_publish"); ?>/?id=<?=$entry->getId();?>">publish</a> |
									<?php endif; ?>
									<a href="<?=$this->getUrl("entry_delete"); ?>/?id=<?=$entry->getId();?>">delete</a> |
									<a href="<?=$this->getUrl("entry_edit"); ?>/?id=<?=$entry->getId();?>">edit</a>
								</div>
								<?php endif; ?>
								<div class="reviewMark">This entry must be reviewed by an admin.</div>
							</div>

							<div>
								<a class="author" href="mailto:<?php echo $entry->getUser()->getEmail(); ?>">
									<?php echo $entry->getUser()->getName(); ?>
								</a>
								on
								<div class="date"><?php echo $entry->getDate(); ?></div>
							</div>
							<p class="entryText"><?php echo $entry->getText(); ?></p>
						</div>
					<?php endforeach; ?>

				</div>
				
			</div>
			<div class="userBox">
				<?php if(!isset($this->userData)) : ?>
					<a href="<?=$this->getUrl("login"); ?>">login to write a new entry</a>
				<?php else: ?>
					Logged in as <?=$this->userData->getName();?>
					<a href="<?=$this->getUrl("logout"); ?>">logout</a>
				<?php endif; ?>
			</div>

			<footer>
				<p>&copy; 2013 by Michael Rotmanov</p>
			</footer>
		</div>
	</body>
</html>
